// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
import PdfController from "./pdf_controller"
import QuoteActionsController from "./quote_actions_controller"

application.register("quote-actions", QuoteActionsController)
application.register("removals", RemovalsController)
application.register("pdf", PdfController)
