
services:
  web:
    image: 343218204168.dkr.ecr.ap-south-1.amazonaws.com/quote-editor-prod:latest
    container_name: rails_app
    restart: always
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    
    command: >
      bash -c "
        echo '🚀 Starting Rails...' &&
        /wait-for-db.sh &&
        bundle exec rails db:prepare &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -b 0.0.0.0 -e production
      "

  sidekiq:
    image: 343218204168.dkr.ecr.ap-south-1.amazonaws.com/quote-editor-prod:latest
    container_name: sidekiq_worker
    environment:
      RAILS_ENV: production
    command: >
      bash -c "
        /wait-for-db.sh &&
        bundle exec sidekiq -e production
      "
    env_file:
      - .env.production

volumes:
  postgres_data:
